account_id = "210f8164cfcc2d406b36bad41c5d8e10"
name = "trossen"
type = "webpack"
workers_dev = true
vars = { DEVELOPMENT = true }
site = { bucket = "./public" }
kv_namespaces = [
  { binding = "MY_KV", id = "557eac331afe43f59cfbd8d606401996", preview_id = "9a84a6d3d4554340b4d9a74e740d9bd0" }
]

[env.staging]
vars = { STAGING = true }
route = "dev.trossen.nu/*"

[env.production]
vars = { PRODUCTION = true }
# The ID of the domain to deploying to
zone_id = "27d7e03538e0fbe4b46009c314f18d9a"

# The route pattern your Workers application will be served at
route = "trossen.nu/*"

kv_namespaces = [
  { binding = "MY_KV", id = "b4f39e8c4f9945e7b75d954ca0f70a24" }
]