account_id = "210f8164cfcc2d406b36bad41c5d8e10"
name = "trossen"
type = "webpack"
workers_dev = true
vars = { ENVIRONMENT = "dev" }
site = { bucket = "./public" }
kv_namespaces = [
  { binding = "DATABASE", id = "8a328597485d447996335454f30013c6", preview_id = "bc950d7746584c2fabd6fc394083465e" }
]

[env.staging]
vars = { ENVIRONMENT = "staging" }
route = "dev.trossen.nu/*"

[env.production]
vars = { ENVIRONMENT = "production" }
# The ID of the domain to deploying to
zone_id = "27d7e03538e0fbe4b46009c314f18d9a"

# The route pattern your Workers application will be served at
route = "trossen.nu/*"

kv_namespaces = [
  { binding = "DATABASE", id = "6e34c60e251d426eb27bf08b2c3484f4" }
]